/**
 * modules/maplestory/custom-events.js — 3 custom server events for MapleStory Cosmic.
 *
 * Creates event scripts in workspace/Cosmic/scripts/event/ using the OdinMS
 * event script API (em object + Java interop). These are server-wide boost events
 * that can be triggered by GMs or on a schedule.
 *
 * Events:
 *   CosmicExpWeekend  — Doubles the server EXP rate for a weekend event
 *   CosmicDropFest    — Doubles the server drop rate to celebrate milestones
 *   CosmicGoldRush    — Doubles the server meso rate to help new players gear up
 *
 * All 3 follow the same pattern seen in 2xEvent.js:
 *   - init() loads the event
 *   - start() activates the boost and broadcasts a world announcement
 *   - stop() reverts the boost and broadcasts a "ended" message
 *   - All required OdinMS event hooks have no-op stubs
 *
 * Idempotent — skips writing if script already exists.
 */

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { createLogger } from '../../lib/logger.js';

const log = createLogger('maplestory:events');

const EVENT_DIR = join(process.cwd(), 'workspace', 'Cosmic', 'scripts', 'event');

// ── Event Definitions ─────────────────────────────────────────────────────────

/**
 * Each event:
 *   name          — script filename (without .js) — also the event's registration name
 *   title         — human-readable title
 *   description   — what the event does
 *   normalRate    — the baseline rate (matches config.yaml: exp_rate=10, drop_rate=5, meso_rate=5)
 *   boostedRate   — the event rate
 *   rateProperty  — which world rate to modify ('Exp'|'Drop'|'Meso')
 *   startMessage  — broadcast message when event starts
 *   stopMessage   — broadcast message when event ends
 */
export const CUSTOM_EVENTS = [
  {
    name: 'CosmicExpWeekend',
    title: 'Cosmic EXP Weekend',
    description: 'Doubles server EXP rate from 10x → 20x for weekend events.',
    normalRate: 10,
    boostedRate: 20,
    rateProperty: 'Exp',
    startMessage: '[Cosmic Event] The Cosmic EXP Weekend has begun! Experience rates are now DOUBLED (20x) for all players. Log in, grind hard, and level up! This event is limited time — make it count!',
    stopMessage: '[Cosmic Event] The Cosmic EXP Weekend has ended. Experience rates have returned to normal (10x). Thanks for participating — see you at the next event!',
  },
  {
    name: 'CosmicDropFest',
    title: 'Cosmic Drop Fest',
    description: 'Doubles server drop rate from 5x → 10x for drop-hunting events.',
    normalRate: 5,
    boostedRate: 10,
    rateProperty: 'Drop',
    startMessage: '[Cosmic Event] Drop Fest is NOW ACTIVE! Item drop rates have been doubled (10x). This is the perfect time to farm equipment, materials, and rare drops. Happy hunting!',
    stopMessage: '[Cosmic Event] Drop Fest has concluded. Item drop rates are back to normal (5x). Hope you found some great loot — see you at the next Drop Fest!',
  },
  {
    name: 'CosmicGoldRush',
    title: 'Cosmic Gold Rush',
    description: 'Doubles server meso drop rate from 5x → 10x to help players gear up.',
    normalRate: 5,
    boostedRate: 10,
    rateProperty: 'Meso',
    startMessage: '[Cosmic Event] Gold Rush is underway! Meso drop rates have been doubled (10x). Stock up on mesos, buy those upgrades, and get your gear sorted. The vaults are open — go get rich!',
    stopMessage: '[Cosmic Event] Gold Rush has ended. Meso drop rates are back to normal (5x). Hopefully your wallets are heavier than before — until next time!',
  },
];

// ── Script Generator ──────────────────────────────────────────────────────────

/**
 * Generate a complete OdinMS-compatible event JavaScript script.
 * Follows the pattern of 2xEvent.js: init → start/stop with Java interop → filler stubs.
 */
function generateEventScript(event) {
  const { name, title, description, normalRate, boostedRate, rateProperty, startMessage, stopMessage } = event;

  const setter = `world.set${rateProperty}Rate`;

  return `/* ${title}
 * ${description}
 *
 * Trigger: Call start() to activate, stop() to deactivate.
 * Can be wired to em.scheduleAtTimestamp() for timed events.
 *
 * Generated by modules/maplestory/custom-events.js
 */

var eventTimer = null;

function init() {
    // Event loaded — call start() to activate, stop() to deactivate.
    // Example timed activation (unix ms timestamp):
    // eventTimer = em.scheduleAtTimestamp("start", 1741100000000);
}

function cancelSchedule() {
    if (eventTimer != null) {
        eventTimer.cancel(true);
        eventTimer = null;
    }
}

function start() {
    var Server = Java.type('net.server.Server');
    var PacketCreator = Java.type('tools.PacketCreator');
    var world = Server.getInstance().getWorld(em.getChannelServer().getWorld());
    ${setter}(${boostedRate});
    world.broadcastPacket(PacketCreator.serverNotice(6, "${startMessage.replace(/"/g, '\\"')}"));
}

function stop() {
    var Server = Java.type('net.server.Server');
    var PacketCreator = Java.type('tools.PacketCreator');
    var world = Server.getInstance().getWorld(em.getChannelServer().getWorld());
    ${setter}(${normalRate});
    world.broadcastPacket(PacketCreator.serverNotice(6, "${stopMessage.replace(/"/g, '\\"')}"));
}

// ── Required OdinMS event stubs ──────────────────────────────────────────────

function dispose() {}
function setup(eim, leaderid) {}
function afterSetup(eim) {}
function monsterValue(eim, mobid) { return 0; }
function playerEntry(eim, player) {}
function playerExit(eim, player) {}
function playerLeft(eim, player) {}
function leftParty(eim, player) {}
function disbandParty(eim, player) {}
function playerDisconnected(eim, player) {}
function playerUnregistered(eim, player) {}
function playerDead(eim, player) {}
function playerRevive(eim, player) { return true; }
function changedMap(eim, player, mapid) {}
function changedLeader(eim, leader) {}
function monsterKilled(mob, eim) {}
function allMonstersDead(eim) {}
function clearPQ(eim) {}
function scheduledTimeout(eim) {}
function timeOut(eim) {
    if (eim.getPlayerCount() > 0) {
        var pIter = eim.getPlayers().iterator();
        while (pIter.hasNext()) {
            var player = pIter.next();
            player.dropMessage(6, "The event has ended.");
            playerExit(eim, player);
        }
    }
    eim.dispose();
}
`;
}

// ── Deploy ────────────────────────────────────────────────────────────────────

/**
 * Deploy all 3 custom event scripts to workspace/Cosmic/scripts/event/.
 * Idempotent — skips existing scripts.
 */
export function deployCustomEvents() {
  if (!existsSync(EVENT_DIR)) {
    mkdirSync(EVENT_DIR, { recursive: true });
    log.info({ dir: EVENT_DIR }, 'Created event scripts directory');
  }

  const results = [];

  for (const event of CUSTOM_EVENTS) {
    const filePath = join(EVENT_DIR, `${event.name}.js`);

    if (existsSync(filePath)) {
      log.debug({ name: event.name }, 'Event script already exists, skipping');
      results.push({ name: event.name, title: event.title, created: false, path: filePath });
      continue;
    }

    const code = generateEventScript(event);
    writeFileSync(filePath, code, 'utf-8');

    log.info({ name: event.name, title: event.title }, 'Event script deployed');
    results.push({ name: event.name, title: event.title, created: true, path: filePath });
  }

  const created = results.filter(r => r.created).length;

  log.info({ created, total: CUSTOM_EVENTS.length }, 'Custom events deployment complete');

  return {
    success: true,
    total: CUSTOM_EVENTS.length,
    created,
    skipped: CUSTOM_EVENTS.length - created,
    events: results,
    note: created > 0
      ? 'Event scripts written. Restart server to load them. Activate in-game via GM commands or em.scheduleAtTimestamp().'
      : 'All event scripts already deployed.',
  };
}

/**
 * Check deployment status of all custom events.
 */
export function getCustomEventStatus() {
  return {
    eventDir: EVENT_DIR,
    events: CUSTOM_EVENTS.map(event => {
      const filePath = join(EVENT_DIR, `${event.name}.js`);
      return {
        name: event.name,
        title: event.title,
        description: event.description,
        normalRate: event.normalRate,
        boostedRate: event.boostedRate,
        rateProperty: event.rateProperty,
        scriptExists: existsSync(filePath),
      };
    }),
  };
}

/**
 * Get a human-readable summary of all custom events.
 */
export function getCustomEventSummary() {
  return CUSTOM_EVENTS.map(e => ({
    name: e.name,
    title: e.title,
    effect: `${e.rateProperty} rate: ${e.normalRate}x → ${e.boostedRate}x`,
    startMessage: e.startMessage.slice(0, 80) + '...',
  }));
}
